services:
  - type: web
    name: encypherist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      echo "Starting application initialization..."
      cd /opt/render/project/src
      PYTHONPATH=/opt/render/project/src LOG_LEVEL=DEBUG FLASK_APP=app.py FLASK_ENV=production python -c "from app import app, db; app.app_context().push(); db.create_all()" || exit 1
      echo "Application initialization completed. Starting server..."
      PYTHONPATH=/opt/render/project/src FLASK_APP=app.py FLASK_ENV=production gunicorn app:app --timeout 120 --workers 4 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: encypherist_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SQLALCHEMY_ECHO
        value: true
      - key: UPLOAD_FOLDER
        value: static/uploads
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      - key: ALLOWED_EXTENSIONS
        value: png,jpg,jpeg,gif,pdf
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: REMEMBER_COOKIE_SECURE
        value: true
      - key: SESSION_COOKIE_HTTPONLY
        value: true
      - key: REMEMBER_COOKIE_HTTPONLY
        value: true
      - key: PERMANENT_SESSION_LIFETIME
        value: 1800
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: false
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: encypherist_db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: LOG_LEVEL
        value: DEBUG
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
    databases:
      - name: encypherist_db
        databaseName: encypherist
        user: encypherist
        plan: free 