services:
  - type: web
    name: encypherist
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db init || true
      flask db migrate -m "Initial migration" || true
    startCommand: python init_db.py && gunicorn app:app --timeout 120 --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: encypherist_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SQLALCHEMY_ECHO
        value: false
      - key: UPLOAD_FOLDER
        value: static/uploads
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      - key: ALLOWED_EXTENSIONS
        value: png,jpg,jpeg,gif,pdf
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: REMEMBER_COOKIE_SECURE
        value: true
      - key: SESSION_COOKIE_HTTPONLY
        value: true
      - key: REMEMBER_COOKIE_HTTPONLY
        value: true
      - key: PERMANENT_SESSION_LIFETIME
        value: 1800
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: false
    healthCheckPath: /
    autoDeploy: true
    databases:
      - name: encypherist_db
        databaseName: encypherist
        user: encypherist
        plan: free 