services:
  - type: web
    name: encypherist
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p static/uploads static/images static/posters
    startCommand: python init_db.py && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: encypherist_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SQLALCHEMY_ECHO
        value: false
      - key: UPLOAD_FOLDER
        value: static/uploads
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      - key: ALLOWED_EXTENSIONS
        value: png,jpg,jpeg,gif,pdf
    healthCheckPath: /
    autoDeploy: true
    databases:
      - name: encypherist_db
        databaseName: encypherist
        user: encypherist
        plan: free 