services:
  - type: web
    name: encypherist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgres://postgres:postgres@localhost:5432/encypherist
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 